apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nginx-tls-cert
spec:
  secretName: nginx-tls-cert
  dnsNames:
  - cust4.ipradr.com
  acme:
    config:
    - http01:
        ingressClass: traefik
      domains:
      - cust4.ipradr.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer