---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nginx-tls-cert-prod
spec:
  secretName: nginx-tls-cert-prod
  issuerRef:
    name: letsencrypt-prod
  commonName: cust4.ipradr.com
  acme:
    config: 
      - http01:
          ingress: node-app-ingress
        domains:
          - cust4.ipradr.com
