apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt
  labels:
    app: letsencrypt
spec:
  template:
    metadata:
      name: letsencrypt
      labels:
        app: letsencrypt
    spec:
      containers:
      - image: sjenning/kube-nginx-letsencrypt:0.8.1-1
        name: letsencrypt
        imagePullPolicy: Always
        ports:
        - name: letsencrypt
          containerPort: 80
        env:
        - name: DOMAINS
          value: cust4.ipadar.com,www.cust4.ipadar.com
        - name: EMAIL
          value: testcicd2019@gmail.com
        - name: SECRET
          value: nginx-tls-cert
        - name: DEPLOYMENT
          value: nginx
      restartPolicy: Never
