
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-docker-pipeline-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    traefik.frontend.passHostHeader: "false"
    traefik.frontend.priority: "1"
spec:
  rules:
  - host: cust3.104.154.19.21.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-docker-pipeline
          servicePort: 3000
tls:
- secretName: nginx-tls-cert
    hosts:
    - cust3.104.154.19.21.xip.io